# Generated by Django 3.0.5 on 2020-04-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenblacklist',
            old_name='access_toekn',
            new_name='access_token',
        ),
    ]
